apiVersion: v1
kind: Pod
metadata:
  name: security-privileges-demo
spec:
  containers:
    - name: security-privileges-demo
      image: alpine:3.2
      command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
      securityContext:
        privileged: true
